// <auto-generated />
using System;
using EFDataAccessLibrary.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFDataAccessLibrary.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("EFDataAccessLibrary.Models.Classes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Class_Name");
                });

            modelBuilder.Entity("EFDataAccessLibrary.Models.Countries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CountryName");
                });

            modelBuilder.Entity("EFDataAccessLibrary.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClassesId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CountriesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassesId");

                    b.HasIndex("CountriesId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EFDataAccessLibrary.Models.Student", b =>
                {
                    b.HasOne("EFDataAccessLibrary.Models.Classes", null)
                        .WithMany("Students")
                        .HasForeignKey("ClassesId");

                    b.HasOne("EFDataAccessLibrary.Models.Countries", null)
                        .WithMany("Students")
                        .HasForeignKey("CountriesId");
                });

            modelBuilder.Entity("EFDataAccessLibrary.Models.Classes", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("EFDataAccessLibrary.Models.Countries", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
